---
- name: Install HashiCorp Vault
  hosts: fedora2
  vars:
    ip_addr: 192.168.122.221
  tasks:
    - name: Configure HashiCorp Vault repository
      ansible.builtin.yum_repository:
        name: HashiCorp
        description: HashiCorp Vault repository
        baseurl: https://rpm.releases.hashicorp.com/fedora/$releasever/$basearch/stable
        state: present
        enabled: true
        gpgkey: https://rpm.releases.hashicorp.com/gpg
        gpgcheck: true
    - name: Install HashiCorp Vault
      ansible.builtin.dnf:
        name: vault
        state: present
    - name: Start & enable vault
      ansible.builtin.service:
        name: vault
        state: started
        enabled: yes
    - name: Set environment variables
      ansible.builtin.lineinfile:
        path: /etc/vault.d/vault.env
        line: "{{ item }}"
        create: yes
      loop: 
        - "VAULT_ADDR=https://{{ ip_addr }}:8200"
        - "VAULT_SKIP_VERIFY=true"
      notify:
        - Restart vault
    - name: Open port 8200 in firewalld
      ansible.posix.firewalld:
        port: 8200/tcp
        permanent: true
        immediate: true
        state: enabled

  handlers:
    - name: Restart vault
      ansible.builtin.service:
        name: vault
        state: restarted

# Installation instruction Linux -> https://developer.hashicorp.com/vault/downloads#linux
