---
- name: Login with token
  hosts: fedora2
  vars_files:
    - vault_secrets.yml
  vars:
    vault_auth_method: userpass
    vault_address: https://192.168.122.221:8200
    vault_user: demo
    vault_user_mount: xforcers
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Set variables
      ansible.builtin.set_fact:
        my_password: "{{ lookup('ansible.builtin.password', '/dev/null', chars=['ascii_lowercase', 'digits'], length=8) }}"
        hostname: "{{ ansible_fqdn }}"
    - name: Create user
      ansible.builtin.user:
        name: testuser
        password: "{{ my_password | password_hash('sha512') }}"
    - name: Authenticate and retreive token
      community.hashi_vault.vault_login:
        url: "{{ vault_address }}"
        auth_method: "{{ vault_auth_method }}"
        username: "{{ vault_user }}"
        password: "{{ vault_user_password }}"
        validate_certs: false
        mount_point: "{{ vault_user_mount }}"
      register: auth_result
    - name: Register client token
      ansible.builtin.set_fact:
        vault_client_token: "{{ auth_result.login.auth.client_token }}"
    - name: Put password in Hashicorp Vault
      ansible.builtin.uri:
        url: "{{ vault_address }}/v1/secret_storage/data/{{ hostname }}"
        method: POST
        headers:
          X-Vault-Token: "{{ vault_client_token }}"
        body_format: json
        body:
          data:
            password: "{{ my_password }}"
        status_code: 200
        validate_certs: false
