---
- name: Login with token
  hosts: fedora2
  vars_files:
    - vault_secrets.yml
  vars:
    vault_auth_method: token
    vault_address: https://192.168.122.221:8200
    vault_user: demo
  tasks:
    - name: Check if 'xforcers' path already exists
      ansible.builtin.uri:
        url: "{{ vault_address }}/v1/sys/auth"
        method: GET
        headers:
          X-Vault-Token: "{{ vault_root_token }}"
        return_content: true
        validate_certs: false
      register: auth_path
    - name: Enable userpass auth method in path xforcers
      ansible.builtin.uri:
        url: "{{ vault_address }}/v1/sys/auth/xforcers"
        method: POST
        headers:
          X-Vault-Token: "{{ vault_root_token }}"
        body_format: json
        body:
          type: "userpass"
          description: "authenticatie methode gebasseerd op username / password"
          config:
            default_lease_ttl: "1h"
            max_lease_ttl: "1d"
            token_type: "service"
        status_code: 204
        validate_certs: false
      when: "'xforcers/' not in auth_path.json"
      ignore_errors: true
    - name: Create a policy
      ansible.builtin.uri:
        url: "{{ vault_address }}/v1/sys/policies/acl/demo_policy"
        method: POST
        headers: 
          X-Vault-Token: "{{ vault_root_token }}"
        body_format: json
        body:
          policy: "{{ lookup('template', 'templates/demo_policy.hcl.j2') }}"
        status_code: 204
        validate_certs: false
    - name: Create a user
      ansible.builtin.uri:
        url: "{{ vault_address }}/v1/auth/xforcers/users/{{ vault_user }}"
        method: POST
        headers: 
          X-Vault-Token: "{{ vault_root_token }}"
        body_format: json
        body: 
          password: "{{ vault_user_password }}"
          token_policies: ["demo_policy"]
        status_code: 204
        validate_certs: false
    - name: Enable kv secret engine
      ansible.builtin.uri:
        url: "{{ vault_address }}/v1/sys/mounts/secret_storage"
        method: POST
        headers: 
          X-Vault-Token: "{{ vault_root_token }}"
        body_format: json
        body: 
          type: kv 
          options:
            version: "2"
        status_code: 204
        validate_certs: false
# https://developer.hashicorp.com/vault/api-docs/system/seal-status
# API Docs: https://developer.hashicorp.com/vault/api-docs
# Create a policy: https://developer.hashicorp.com/vault/api-docs/system/policies
# https://developer.hashicorp.com/vault/api-docs/system/mounts#type
