---
- name: Login with token
  hosts: fedora2
  vars_files:
    - vault_secrets.yml
  vars:
    vault_user: demo
    vault_user_mount: xforcers
    vault_auth_method: userpass
    vault_address: https://192.168.122.221:8200
  tasks:
    - name: Authenticate and retreive token
      community.hashi_vault.vault_login:
        url: "{{ vault_address }}"
        auth_method: "{{ vault_auth_method }}"
        username: "{{ vault_user }}"
        password: "{{ vault_user_password }}"
        mount_point: "{{ vault_user_mount }}"
        validate_certs: false
      register: auth_result
    - name: Register client token
      ansible.builtin.set_fact:
        vault_client_token: "{{ auth_result.login.auth.client_token }}"
    - name: Check old password
      ansible.builtin.uri:
        url: "{{ vault_address }}/v1/secret_storage/data/{{ ansible_hostname }}?version=1"
        method: GET
        headers:
          X-Vault-Token: "{{ vault_client_token }}"
        body_format: json
        status_code: 200
        validate_certs: false
      register: password_version
    - name: Put password in Hashicorp Vault
      ansible.builtin.uri:
        url: "{{ vault_address }}/v1/secret_storage/data/{{ ansible_hostname }}"
        method: POST
        headers:
          X-Vault-Token: "{{ vault_client_token }}"
        body_format: json
        body:
          data:
            password: "{{ password_version.json.data.data.password }}"
        status_code: 200
        validate_certs: false
