---
- name: Check vault status
  hosts: fedora2
  vars:
    vault_host: 192.168.122.221
  tasks:
    - name: Check vault status
      ansible.builtin.uri:
        url: "https://{{ vault_host }}:8200/v1/sys/seal-status"
        method: GET
        body_format: json
        status_code: 200
        validate_certs: false
      register: seal_status
    - name: Show vaul status
      ansible.builtin.debug:
        var: seal_status.json

# https://developer.hashicorp.com/vault/api-docs/system/seal-status
